stages:
  - test
  - build-push
  - pack
  - deploy
  
.ssh_defaults:
  image: kroniak/ssh-client
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p $REMOTE_PORT $REMOTE_HOST >> ~/.ssh/known_hosts
    - chmod 664 ~/.ssh/known_hosts

test:
  rules:
    - if: '$CI_COMMIT_TAG != null'
      when: manual
  stage: test
  image: python:3.8
  before_script:
   - pip install -r requirements.txt
  script:
    - python manage.py test school users

build-push:
  rules:
    - if: '$CI_COMMIT_TAG != null'
      when: manual
  image: docker:20.10

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''

  services:
    - docker:20.10.16-dind
  stage: pack

  before_script:
    - export IMAGE=$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - time docker build -t $IMAGE -f docker/Dockerfile .
    - docker push $IMAGE

deploy:
    when: manual
    extends:
      .ssh_defaults
    stage: deploy
    before_script:
    - export IMAGE=$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    script:
    - echo test
    