stages:
  - test
  - build-push

test:
  stage: test
  image: python:3.8
  before_script:
   - pip install -r requirements.txt
  script:
    - python manage.py test school users

build-push:
  needs:
    - test
  rules:
    - if: '$CI_COMMIT_TAG != null'
      when: manual
  image: docker:stable

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''

  before_script:
    - export IMAGE=$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - time docker build -t $IMAGE -f docker/Dockerfile .
    - docker push $IMAGE

